### PR TITLE
Update to ember 4.7

### LINKED ISSUE #42: Doesn't support EmberJS v4.x.x
**Describe the bug**
CI is failing trying to build this for ember-canary and ember-beta, I think this means it's failing on 4.x.x in general. 

**To Reproduce**
Run the full test suite and watch it fail.

**Expected behavior**
Should support EmberJS v4.x.x and pass all tests.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by MinThaMie**
Fixes #42 

This was introduced
Screenshot_2022-10-19_at_16 09 41
and it's known: https://discord.com/channels/480462759797063690/486548111221719040/1017797665246953472

It might be one of our dependencies calling a bowerAPI.

### CODE REVIEW

**Comment by MelSumner** [comment]
Ok are you able to figure out which dependency it is?

**Comment by MelSumner** [comment]
Can you try running these tests again so I can see what's going on here? Thanks!

**Comment by MinThaMie** [comment]
I'm not sure how to trigger a rerun :(

**Comment by hergaiety** [comment]
Not sure why it didn't have the option. So I tried _turning it off and back on again_ and it's running.

**Review by MelSumner — APPROVED** [review]

**Pull request closed without merging**
